#! /bin/sh
# /etc/init.d/Robot_server
#

SERVER='/usr/local/lib/python2.7/dist-packages/Robot_Server/RobotServer.py'

# Some things that run always
touch /var/lock/Robot_server

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    echo "Starting script Robot_server"
    /usr/bin/env python $SERVER --start --daemon
    ;;
  stop)
    echo "Stopping script Robot_server"
    /usr/bin/env python $SERVER --stop
    ;;
  restart)
    echo "Starting script Robot_server"
    /usr/bin/env python $SERVER --restart --daemon
    ;;
  *)
    echo "Usage: /etc/init.d/Robot_server {start|stop|restart}"
    exit 1
    ;;
esac

exit 0