#! /bin/sh
# copy service file
#cp init/Robot_Server /etc/init.d
cp /usr/local/bin/Robot_Server /etc/init.d
# set up service starting/stopping
update-rc.d Robot_Server defaults
# start service
service Robot_Server start