#! /bin/sh
# copy service file
#cp init/Wall-E_Server /etc/init.d
cp /usr/local/bin/Wall-E_Server /etc/init.d
# set up service starting/stopping
update-rc.d Wall-E_Server defaults
# start service
service Wall-E_Server start